require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.melange-nvim")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
